services:
  web:
    build: .
    image: web
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "alembic upgrade head && fastapi dev app/main.py --host 0.0.0.0"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  celery-worker:
    image: web
    command: celery -A app.celery_app worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      web:
        condition: service_started
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  celery-beat:
    image: web
    command: celery -A app.celery_app beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      web:
        condition: service_started
      redis:
        condition: service_healthy

  redis:
    image: redis:8.6-alpine
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
